### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Nikatec** [lvnvceo/OllamaDroid#1]
App crashes as soon as Settings gear is pressed

**Comment by Ac1drainn** [comment]
Hello! Can you show me a logcat of the error?

**Comment by sans202** [comment]
Same here!

**Comment by NielSync** [comment]
> Hello! Can you show me a logcat of the error?

FATAL EXCEPTION: main
Process: com.lvnvceo.ollamadroid, PID: 13613
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lvnvceo.ollamadroid/com.lvnvceo.ollamadroid.SettingsActivity}: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3822)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3963)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2468)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1260)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1633)
	at okhttp3.Request$Builder.url(Request.kt:184)
	at com.lvnvceo.ollamadroid.SettingsActivity.onCreate(SettingsActivity.java:70)
	at android.app.Activity.performCreate(Activity.java:8621)
	at android.app.Activity.performCreate(Activity.java:8599)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1459)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3804)
	... 12 more

**Comment by Ac1drainn** [comment]
No longer maintained. Please find an alternative. If you do, please reply with a link here and I'll add it to the README.md
